# Generated by Django 4.0.5 on 2023-07-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='None', upload_to='')),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
