# Generated by Django 4.0.5 on 2023-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(upload_to='myimage'),
        ),
    ]
