# Generated by Django 4.0.5 on 2023-07-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_image_alter_data_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
