# Generated by Django 4.0.5 on 2023-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datareceipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='myimage2')),
                ('description', models.TextField()),
            ],
        ),
    ]
